### ISSUE TITLE
Dead Plant

### ISSUE THREAD

**Issue by BlurOne-GIT** [juanifogo/WetPlantFinaPlis#1]
## Issue:
One Plant was killed by this project.

## Steps to replicate:
- Put plant in machine.
- Use machine.

### Expected result:
Plant should live being watered and refreshed regularly.

### Real result:
Plant drowned.

**Comment by juanifogo** [comment]
Hi Blur! We are sorry to hear that. Our analysts have concluded that this issue is not related to our product but rather your dumb plant, so its not our problem.

**Comment by BlurOne-GIT** [comment]
R.I.P. Pincel.

**Comment by BlurOne-GIT** [comment]
R.I.P. Pincel.
